# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9625d75f-c563-4a4b-a2dd-9f9865f1fef6";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime" "ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9625d75f-c563-4a4b-a2dd-9f9865f1fef6";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CC60-6F6D";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9b4cb56a-ddb3-4ea0-8063-636dda6598a2"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
